-- 1) Customers
CREATE TABLE customers (
  customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(100) NOT NULL,
  region        VARCHAR2(50) NOT NULL
);

-- 2) Products
CREATE TABLE products (
  product_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(100) NOT NULL,
  category      VARCHAR2(50)
);

-- 3) Transactions (sales)
CREATE TABLE transactions (
  transaction_id NUMBER PRIMARY KEY,
  customer_id    NUMBER NOT NULL,
  product_id     NUMBER NOT NULL,
  sale_date      DATE NOT NULL,
  amount         NUMBER(12,2) NOT NULL,
  CONSTRAINT fk_trx_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_trx_product  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- Helpful indexes
CREATE INDEX idx_trx_sale_date ON transactions(sale_date);
CREATE INDEX idx_trx_customer ON transactions(customer_id);
CREATE INDEX idx_trx_product ON transactions(product_id);
